# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_num', models.IntegerField()),
                ('stu_subj', models.CharField(choices=[('CE', '通信工程'), ('IS', '专业领导')], max_length=2)),
                ('graduation_year', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
