# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 03:14
from __future__ import unicode_literals

import apps.thesis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('file', models.CharField(choices=[('MANDATE', '01任务书'), ('SCHEDULE1', '02指导计划表(教师)'), ('SCHEDULE2', '03指导计划表(学生)'), ('PROPOSAL', '04开题报告'), ('CHECKLIST', '05中期检查表'), ('PPT1', '06中期检答辩PPT'), ('DEFENCE', '07答辩申请表'), ('ADVICE', '08导教师意见'), ('REVIEW', '09评阅意见'), ('THESIS', '10论文'), ('PPT2', '11答辩PPT'), ('SCORE', '12成绩登记表'), ('SOURCECODE', '13源代码')], max_length=10)),
                ('upload_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='thesis',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='stu_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='stu_subj',
            field=models.CharField(choices=[('CE', '通信工程'), ('IS', '信息与计算科学')], max_length=2),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=100, validators=[apps.thesis.models.validator_title]),
        ),
        migrations.AddField(
            model_name='thesislog',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_log', to='thesis.Thesis'),
        ),
    ]
