# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_auto_20171207_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesislog',
            old_name='last_update_time',
            new_name='last_upload_time',
        ),
    ]
